export default function Response({response,aiGenerated}){
    let aiGeneratedText=""
    console.log(aiGenerated)
    if(aiGenerated=="The Text is generated by AI."){
        aiGeneratedText="generated using AI"
    }
    else{
        aiGeneratedText="written by human"
    }
    return (
        <div class="bg-myWhite text-center rounded-lg pt-3 pb-3 pl-1 pr-1 mt-10">
            <h2 class="text-2xl text-myRed font-bold">Result</h2>
            <p class="mt-2 text-lg font-bold">Based on the obtained data, our AI model considers the news to be false with a probability of <span class="text-myRed font-extrabold">{response}%</span>. 
            Also, according to our model, the text was {aiGeneratedText}.</p>
        </div>
    )
}